name: Trigger Other Repos

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflows in All Repositories
        env:
          TOKEN: ${{ secrets.git }}
        run: |
          repos=("maven-web-application" "Shopping-Cart")
          for repo in "${repos[@]}"; do
            echo "Triggering workflow in $repo..."
            curl -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $TOKEN" \
              https://api.github.com/repos/angle-sravani/$repo/actions/workflows/main.yml/dispatches \
              -d '{"ref":"main"}'
          done
